### ISSUE TITLE
Debugging failing transactions

### ISSUE THREAD

**Issue by stickbreaker** [stickbreaker/OneWire#3]
Continuation of issue with [Arduino-Esp32#1335](https://github.com/espressif/arduino-esp32/issues/1335) with @OmarAlkassab .

**Comment by OmarAlkassab** [comment]
Dear @stickbreaker, actually I can’t go to the laboratory to make the test with the logic analyzer, I am actually in home due to some problems in my country. I noticed now that the task hangs after some hours! The task hangs when the task is moved to the core 1.

**Comment by stickbreaker** [comment]
@OmarAlkassab Well, when you have some time to build an example that replicates the problem I'll take a look. Until I have something that duplicates the problem I can't try fixing it.

Chuck.

**Comment by stickbreaker** [comment]
Closed due to inactivity.
